- name: Configurar servidores Ubuntu
  hosts: servidores
  become: yes
  tasks:
    - name: Actualizar paquetes
      apt:
        update_cache: yes

    - name: Crear usuario itla
      user:
        name: itla
        state: present

    - name: Crear carpeta app
      file:
        path: /home/itla/app
        state: directory
        owner: itla
        mode: '0755'

    - name: Crear archivo hola.txt
      copy:
        dest: /home/itla/app/hola.txt
        content: "Hola desde Ansible"
        owner: itla
        mode: '0644'

    - name: Instalar cowsay y htop
      apt:
        name:
          - cowsay
          - htop
        state: present